In [1]:
import numpy as np
import pandas as pd

In [21]:
np.random.randint(0, 2)

1

In [25]:
[np.random.randint(0, 2) for _ in range(20)]

[1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0]

In [30]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [39]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [32]:
a.shape

(6,)

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])