In [1]:
import numpy as np
from scipy.optimize import minimize, LinearConstraint

In [2]:
n_buyers = 10
n_shares = 15

In [3]:
np.random.seed(10)
prices = np.random.random(n_buyers)
money_available = np.random.randint(1, 4, n_buyers)

In [4]:
n_shares_per_buyer = money_available / prices
print(prices, money_available, n_shares_per_buyer, sep="\n")

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]
[1 1 1 3 1 3 3 2 1 1]
[ 1.29647768 48.18824404  1.57816269  4.00638948  2.00598984 13.34539487
 15.14670609  2.62974258  5.91328161 11.3199242 ]


In [12]:
np.ones(n_buyers)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
constraint = LinearConstraint(np.ones(n_buyers), lb=n_shares, ub=n_shares)

In [6]:
bounds = [(0, n) for n in n_shares_per_buyer]

In [7]:
def objective_function(x, prices):
    return -x.dot(prices)

In [8]:
res = minimize(
    objective_function,
    x0=10 * np.random.random(n_buyers),
    args=(prices,),
    constraints=constraint,
    bounds=bounds,
)

In [9]:
res

     fun: -8.783020157087709
     jac: array([-0.7713207 , -0.02075195, -0.63364828, -0.74880385, -0.49850702,
       -0.22479665, -0.1980629 , -0.76053059, -0.16911077, -0.08833981])
 message: 'Optimization terminated successfully'
    nfev: 187
     nit: 17
    njev: 17
  status: 0
 success: True
       x: array([1.29647768e+00, 0.00000000e+00, 1.57816269e+00, 4.00638948e+00,
       2.00598984e+00, 3.48323773e+00, 0.00000000e+00, 2.62974258e+00,
       6.52515991e-15, 0.00000000e+00])

In [14]:
n_bonds = 10
available_cash = 280

In [15]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)

In [16]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])